### ISSUE TITLE
Download Publisher not working with IATI Decipher

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [pwyf/iati-decipher#106]
Hi Andy,

The Tech Team have just implemented a function on the [Publisher List](https://iatiregistry.org/publisher) page on the Registry, whereby a user can download a list of current publishers in CSV, XLS, XML or JSON format.

However, we have noticed that the function does not work when the user has the IATI Decipher extension on their browser.

Is their something in the Decipher code that is intercepting this function and can anything be done to fix this?

Thanks,
Josh

@PetyaKangalova

**Comment by andylolz** [comment]
Hi @JoshStanleyDevInit,

I no longer work at Publish What You Fund, so it’s best to @ me.

Good detective work – you’re absolutely right that the plugin is at fault here. Apologies if this caused has a headache for the team.

I’m able to recreate the problem in Chrome. Could you confirm that that’s the browser where you’re seeing the problem?

I’ve fixed the bug in 0c804c21. However, the new version of the plugin (v1.5.0) isn’t yet available on the Chrome store (it’s awaiting approval), nor is it on the mozilla add-on store (they seem to have a bug at the moment, so I’m not able to submit it.)

Once it’s on both stores, it should auto-update on users’ machines.

**Comment by samuele-mattiuzzo** [comment]
Thanks @andylolz yes, Chrome is the browser! We'll update once the app gets automatically updated on our ends to confirm it works!

**Comment by samuele-mattiuzzo** [comment]
Chrome's version is now at `1.5.0` https://chrome.google.com/webstore/detail/iati-decipher/akignlamolglcjboilhajenkkkcnohjj

Firefox's version is still at `1.4.4` https://addons.mozilla.org/en-US/firefox/addon/iati-decipher/?src=search

**Comment by andylolz** [comment]
That’s right – I wasn’t able to update the firefox addon. Just waiting on a fix: https://github.com/mozilla/addons/issues/1102

**Comment by andylolz** [comment]
@samuele-mattiuzzo is the issue resolved for you (in Chrome) now?

**Comment by andylolz** [comment]
@JoshStanleyDevInit is the issue resolved for you (in Chrome) now? Thanks

**Comment by JoshStanleyDevInit** [comment]
@andylolz yep all good for me!

Note that I have referenced this issue in the [Discuss post](https://discuss.iatistandard.org/t/new-download-publisher-function-on-registry/1854) I just opened in case anyone else comes across the problem!

Thanks for your quick work on this Andy!!

**Comment by andylolz** [comment]
No problem. I’ll leave this open & assigned to me, so I remember to update the firefox plugin once the issue with mozilla sign-on is sorted.

**Comment by andylolz** [comment]
v1.5.0 is now on the chrome webstore and mozilla add-on store, so I think this is fixed everywhere.

Thanks again for reporting this.
