### ISSUE TITLE
Make the dataset search search on more fields

### ISSUE THREAD

**Issue by andylolz** [pwyf/iati-decipher#93]
Reported by [Matt Geddes on discuss](https://discuss.iatistandard.org/t/show-iati-view-organisation-file-data-with-iati-decipher/1575/2):

> […] because it is so easy to search for a publisher via the browser plugin, I tend to use that rather than going to the registry, but often it means I need to know the ‘correct name’ that the publisher is using. Perhaps this could search a few more fields e.g. the publisher country? For example - to find the German Foreign Ministry file, I tried BMZ, Bundes…, Deutschland, German…and finally ‘Germany’ before I got it - whereas if it could return all publishers based in Germany, it would be easier in many cases.

**Comment by matmaxgeds** [comment]
Thanks for this @andylolz, let me know if there is anything I can help with - explanations, testing etc

**Comment by andylolz** [comment]
Great! So the issue is with how I’m using the registry API. The query that’s run at the moment is:
https://github.com/pwyf/iati-decipher/blob/ccb6e01ee297031232eca4f2c31a96d2d03df6b7/src/js/popup.js#L11

…so e.g.:
https://iatiregistry.org/api/3/action/package_search?fq=extras_filetype:organisation&qf=title&q=germany

So that’s just looking at the title. If you can figure out a better query, let me know! Or if you have a list of the fields that should be searched.

**Comment by matmaxgeds** [comment]
Just a note to say that we are making some progress one this e.g. https://iatiregistry.org/api/3/action/package_search?fq=extras_filetype:organisation&q=BMZ returns files with the search string located outside of the title field - but we are now need to narrow down what it returns e.g. https://iatiregistry.org/api/3/action/package_search?fq=extras_filetype:organisation&q="DE" also returns files with the word 'description' in the returned data which we don't want. More soon.....

**Comment by matmaxgeds** [comment]
Hi Andy - got a pull request coming for this coming from @kndm - a programmer I work with - we have done a few quick tests of a modified plugin and think it works well e.g. "bmz" now picks up the Germany file, "GB" returns all the orgs based in the UK etc, without being information overload or too many false positives. But you might decide that it is better with a narrower search field, or perhaps some other way.....let us know

**Comment by andylolz** [comment]
Looks cool! I’ll test it out very shortly.

**Comment by andylolz** [comment]
Fixed in #96.

**Comment by matmaxgeds** [comment]
@andylolz @kndm - in 1.3.1 a search for 'asdb' isn't bringing up the Asian Development Bank file....i.e. https://iatiregistry.org/api/3/action/package_show?id=asdb-org - which includes the string 'asdb' several times - have we missed a search field?

**Comment by andylolz** [comment]
Just checked, and this was the case at 1.3.0 too – so (thankfully!) unrelated to that change.

It might be worth us checking with CKAN developers (or even on a solr mailing list) to find out the best search string here, since this is not IATI-specific.

**Comment by kndm** [comment]
Upon further inspection it seems some of the fields are not mapped properly, i.e organization_name may not be the name of the field for organization -> name (key)

@andylolz do you happen to have any leads on to where I could better see documentation for these fields returned? :)

**Comment by andylolz** [comment]
@kndm I added a couple of links above:

> The CKAN docs are here: https://docs.ckan.org/en/2.8/api/index.html
> The solr docs are here: https://lucene.apache.org/solr/guide/7_3/common-query-parameters.html

But I think you’d be better off asking a solr mailing list, or possibly a CKAN mailing list.

If you’re happy to keep looking into this, that would be great – I’ll be happy to review and merge a PR.

**Comment by andylolz** [comment]
This was raised again recently by two users separately, both times with the specific example of AfDB / African Development Bank. The former search works, the latter doesn’t (despite it being listed as the organisation name).

**Comment by matmaxgeds** [comment]
@kndm happy for you to skip a bit of Somalia work to have another look at this - maybe you also got a reply to your post on the CKAN forums?

**Comment by andylolz** [comment]
I’ve posted the following: https://lists.okfn.org/pipermail/ckan-dev/2018-December/023005.html

Does that look okay?

Fingers crossed for a response!

**Comment by kndm** [comment]
Thanks for the very detailed info Andy, I will be looking at this (and the
mailing list, though I got no response) in the following hours!

**Comment by andylolz** [comment]
Okay, so it seems like the answer is: [this isn’t possible without changes to the registry API](https://lists.okfn.org/pipermail/ckan-dev/2018-December/023009.html) :(

**Comment by matmaxgeds** [comment]
Ooof/thanks for the detective work - is that something we can request changes to, as from my unenlightened position it is hard to understand why the org title field can't be queried? I guess the alternative is to download all the org files ourselves which isn't particularly appealing.

**Comment by andylolz** [comment]
> from my unenlightened position it is hard to understand why the org title field can't be queried

Yep, same.

> download all the org files ourselves which isn't particularly appealing

That would work, but I’m really not keen to do it because I think the registry API should be able to handle it. I’ll raise a ticket on the registry github, asking about the possibility of a plugin.
